version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3000" # Maps backend container port 3000 to host port 3001
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Maps frontend container port 3000 to host port 3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
